name: myapp
description: A Helm chart template for Kubernetes charts repository
version: 0.0.5
home: https://k8s.community/
sources:
  - https://github.com/geri4/myapp
maintainers:
  - name: Andrey Gerasimov
    email: grsanw@gmail.com
engine: gotpl
